cart/urls.py
from django.urls import path
from .views import cart_detail
from . import views

app_name = "cart"
urlpatterns = [
       path('', views.cart_detail, name='cart_detail'),
       path('add/<int:product_id>/', views.cart_add, name='cart_add'),
       path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

med/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart_app')),
    path('', include('web.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from .views import shop
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('shop/', views.shop, name='shop'),
    path('tovar/', views.tovar, name='tovar'),
    path('partner/', views.partner, name='partner'),
    path('about/', views.about, name='about'),
    path('diplomi/', views.diplomi, name='diplomi'),
    path('innovations/', views.innovations, name='innovations'),
    path('postavshiki/', views.postavshiki, name='postavshiki'),
    path('medkab/', views.medkab, name='medkab'),
    path('sanit/', views.sanit, name='sanit'),
    path('tovar/<int:pk>/', views.tovar.as_view() , name = 'tovar'),
]

cart/models.py
from django.db import models

# Create your models here.

web/models.py
from django.db import models
from PIL import Image
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class Product(models.Model):
    ANGIOLOGYANDMRI ='ANGIOLOGY AND MRI'
    ANESTHESIOLOGYANDRESUSCITATION ='ANESTHESIOLOGY AND RESUSCITATION'
    VETERINARY ='VETERINARY'
    CTSCAN ='CT SCAN'
    LABORATORYFURNITURE ='LABORATORY FURNITURE'
    MEDICALFURNITURE ='MEDICAL FURNITURE'
    METALFURNITURE ='METAL FURNITURE'
    NEONATOLOGY ='NEONATOLOGY'
    CONSUMABLES ='CONSUMABLES'
    STERILIZATIONANDDISINFECTION ='STERILIZATION AND DISINFECTION'
    DENTISTRY ='DENTISTRY'
    ULTRASOUNDDIAGNOSTICS ='ULTRASOUND DIAGNOSTICS'
    PHYSIOTHERAPY ='PHYSIOTHERAPY'
    FUNCTIONALDIAGNOSTICS ='FUNCTIONAL DIAGNOSTICS'
    SURGERY ='SURGERY'
    ENDOCRINOLOGY ='ENDOCRINOLOGY'
    ENDOSCOPY ='ENDOSCOPY'

    CHOICE_GROUP ={
        (ANGIOLOGYANDMRI,'ANGIOLOGY AND MRI'),
        (ANESTHESIOLOGYANDRESUSCITATION, 'ANESTHESIOLOGY AND RESUSCITATION'),
        (VETERINARY, 'VETERINARY'),
        (CTSCAN, 'CT SCAN'),
        (LABORATORYFURNITURE, 'LABORATORY FURNITURE'),
        (MEDICALFURNITURE, 'MEDICAL FURNITURE'),
        (METALFURNITURE, 'METAL FURNITURE'),
        (NEONATOLOGY, 'NEONATOLOGY'),
        (CONSUMABLES, 'CONSUMABLES'),
        (STERILIZATIONANDDISINFECTION, 'STERILIZATION AND DISINFECTION'),
        (DENTISTRY, 'DENTISTRY'),
        (ULTRASOUNDDIAGNOSTICS, 'ULTRASOUND DIAGNOSTICS'),
        (PHYSIOTHERAPY, 'PHYSIOTHERAPY'),
        (FUNCTIONALDIAGNOSTICS, 'FUNCTIONAL DIAGNOSTICS'),
        (SURGERY, 'SURGERY'),
        (ENDOCRINOLOGY, 'ENDOCRINOLOGY'),
        (ENDOSCOPY, 'ENDOSCOPY'),
    }

    id = models.AutoField(primary_key=True)
    quantity = models.IntegerField(default ='1')
    name = models.CharField(max_length=100)
    description = models.TextField()
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    price = models.CharField(max_length=100)
    availability = models.BooleanField()
    group = models.CharField(max_length=50, choices=CHOICE_GROUP, default=SURGERY)
    img = models.ImageField(default='no_image.png', upload_to='product_image')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name}'

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from web.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

web/views.py
from django.shortcuts import render, redirect
from web.models import Product
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm
from cart.forms import CartAddProductForm
from django.db.models import Q

def index(request):
    return render(request, 'web/index.html')

def shop(request):
    product = Product.objects.all()
    context = {
        'pr': product
    }
    return render (request, 'web/shop.html', context)

def about(request):
    return render (request, 'web/about.html')

def partner(request):
    return render (request, 'web/partner.html')

def diplomi(request):
    return render (request, 'web/diplomi.html')

def innovations(request):
    return render (request, 'web/innovations.html')

def postavshiki(request):
    return render (request, 'web/postavshiki.html')

def medkab(request):
    return render (request, 'web/medkab.html')

def sanit(request):
    return render (request, 'web/sanit.html')

class tovar(DetailView):
    model = Product
    template_name = 'web/tovar.html'
    slug_field = "id"

def product_detail (request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'web/tovar.html', {'product': product, 'cart_product_form': cart_product_form})

cart/templates/cart/detail.html
{% extends 'web/main.html' %}
{% load static %}
{% block title_page %}
<title>Товар</title>
{% endblock title_page %}
{% block content %}

 <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>

          {% for item in cart %}
                      {% with product=item.product %}
                          <tr>
                              <td>
                                  <a href="{{ product.get_absolute_url }}">
                                      <img src="
                                          {% if product.img %}
                                              {{ product.img.url }}
                                          {% else %}
                                              {% static 'img/no_image.png' %}
                                          {% endif %}">
                                  </a>
                              </td>
                              <td>{{ product.name }}</td>
                              <td>{{ product.quantity }}</td>
                              <td><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
                              <td class="num">${{ product.price }}</td>
                              <td class="num">${{ item.total_price }}</td>
                          </tr>
                      {% endwith %}
                  {% endfor %}
                  <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'shop:product_list' %}" class="button light">Continue shopping</a>
        <a href="#" class="button">Checkout</a>
    </p>

{% endblock content %}

web/templates/web/about.html
{% extends 'web/main.html' %}
{% load static %}
{% block title_page %}
<title>О нас</title>
{% endblock title_page %}
{% block content %}

<style>
   p {
    padding: 100px;
   }
  </style>
  <p><br>Компания ООО «БМТ-Медтехника» основана в 2005 году и с тех пор зарекомендовала себя как надежный партнер в области комплексного оснащения лечебных учреждений. На сегодняшний день компания значительно увеличила направления своей деятельности и ассортимент поставляемого оборудования.  ООО «БМТ-Медтехника» является эксклюзивным представителем ведущих российских и зарубежных производителей современного медицинского оборудования, таких как Esaote S.p.A., CareFusion (Viasys), Pentax, DGM и ТЗМОИ, Тритон и Zisline, GE (Ohmeda Medical), Mindray и др. Компания принимает активное участие в международных специализированных выставках, где представляет свои товары и услуги.</br>
  <br>Для удобства наших клиентов была увеличена география деятельности компании: открыты филиалы в городах Ижевск и Екатеринбург.</br>
  <br>Среди наших заказчиков - лечебные учреждения республиканского уровня, городские и участковые больницы, частные узкоспециализированные кабинеты и многопрофильные клиники. Всё это благодаря тому, что мы предлагаем широкий  ассортимент оборудования и расходных материалов для полного оснащения лечебного учреждения.  Для наших частных клиентов действуют выставочные торговые залы, в которых представлена в наличии вся продукция, необходимая для лицензирования лечебного учреждения, а также товары для домашнего применения.</br>
  <br>Современное качественное медицинское оборудование — это верный путь к повышению качества оказываемых медицинских услуг!</br></p>

  <footer class="footer">
    <div class="container">
      <div class="footer-logo"><a href="#"><img src="{% static 'img/footer-logo.png' %}" alt=""></a></div>
      <span class="copyright">&copy; 2009-2020 ООО "БМТ". Все права защищены.</span>
      <div class="credits">
      </div>
    </div>
  </footer>
{% endblock content %}

web/templates/web/diplomi.html
{% extends 'web/main.html' %}
{% load static %}
{% block title_page %}
<title>Дипломы</title>
{% endblock title_page %}
{% block content %}

<style>
   .center {
    width: 700px; /* Ширина элемента в пикселах */
    padding: 10px; /* Поля вокруг текста */
    margin: auto; /* Выравниваем по центру */
   }
  </style>
  <div class="center">
    <b>2016 год</b>
 <p>Диплом за плодотворное сотрудничество, актуальность и профессионализм представленной экспозиции на Недели Здравохранения 2016</p>
   <p><img src="{% static 'img/_здравоохранения 2016 (2).jpg' %}" width="310" height="400" alt="">
   </p>

   <p>
     <b>2015 год</b>
  <p>Диплом участника выставки в рамках мероприятий саммита ШОС и БРИКС на Недели Здравохранения 2015</p>
    <p><img src="{% static 'img/_здравоохранения 2015 (2).jpg' %}" width="310" height="400" alt=""></p>
   </p>

   <p>
     <b>2015 год</b>
  <p>Диплом за достойное представление товаров и услуг на рынке РБ и активное участие компании в работе выставке "МЕДИЦИНА 2015"</p>
    <p><img src="{% static 'img/_2015 (2).jpg' %}" width="310" height="400" alt=""></p>
   </p>

   <p>
     <b>2014 год</b>
  <p>Диплом за достойное представление товаров и услуг на рынке РБ и активное участие компании в работе выставке "МЕДИЦИНА 2014"</p>
    <p><img src="{% static 'img/_2014 (2).jpg' %}" width="310" height="400" alt=""></p>
   </p>

   <p>
     <b>2013 год</b>
  <p>Участие компании в выставке "Дентал-Экспо. Стоматология Урала 2013г"</p>
    <p><img src="{% static 'img/_выставка  стоматологии1.jpg' %}" width="310" height="400" alt=""></p>
   </p>

   <p>
     <b>2013 год</b>
  <p>Участие компании в ХХII специализированной международной выставке-форуме "МЕДИЦИНА 2013". Диплом за достойное представление товаров и услуг на рынке РБ и активное участие в работе выставки.</p>
    <p><img src="{% static 'img/_Медицина 2013 Уфа (2).jpg' %}" width="310" height="400" alt=""></p>
   </p>

   <p>
     <b>2012 год</b>
  <p>Участие компании в ХХII специализированной международной выставке-форуме "МЕДИЦИНА 2012". Диплом за достойное представление товаров и услуг на рынке РБ и активное участие в работе выставки.</p>
    <p><img src="{% static 'img/_2012 (1).jpeg' %}" width="310" height="400" alt=""></p>
   </p>

   <p>
     <b>2011 год</b>
  <p>Диплом за достойное представление товаров и услуг на рынке РБ и активное участие компании в ХХ юбилейной международной специализированной выставке "МЕДИЦИНА 2011".</p>
    <p><img src="{% static 'img/_2011 (1).jpeg' %}" width="310" height="400" alt=""></p>
   </p>

   <p>
     <b>2008 год</b>
  <p>Активное участие компании в ХVII международной специализированной выставке "МЕДИЦИНА 2008". Диплом за достойное представление товаров и услуг на рынке РБ.</p>
    <p><img src="{% static 'img/_2008 (1).jpg' %}" width="310" height="400" alt=""></p>
   </p>

   <p>
     <b>2007 год</b>
  <p>Активное участие компании в ХVI международной специализированной выставке "МЕДИЦИНА 2007". Диплом за достойное представление товаров и услуг на рынке РБ.</p>
    <p><img src="{% static 'img/_2007 (2).jpg' %}" width="310" height="400" alt=""></p>
   </p>

{% endblock content %}

web/templates/web/index.html
{% extends 'web/main.html' %}
{% load static %}
{% block title_page %}
<title>Document</title>
{% endblock title_page %}
{% block content %}
  <header class="header" id="header">
    <!--header-start-->
    <div class="container">
      <figure class="logo animated fadeInDown delay-07s">
        <a href="#"><img src="{% static 'img/logo.png' %}" alt=""></a>
      </figure>
      <h1 class="animated fadeInDown delay-07s">Башкирская медицинская техника</h1>
      <ul class="we-create animated fadeInUp delay-1s">
        <li><br>С 2005 года компания БМТ поставляет качественное медицинское оборудование в клиники, больницы и медицинские центры по всей России.</br>
<br>Высокое качество обслуживания, индивидуальный подход и гибкая ценовая политика позволили занять нам достойное место на рынке медтехники. Среди наших постоянных клиентов государственные больницы и частные медицинские учреждения.</br>
<br>В нашем каталоге Вы найдете только самое современное медицинское оборудование для оснащения палаты интенсивной терапии, стоматологического кабинета и хирургии.</br>
<br>Для диагностики и ультразвуковых исследований мы предлагаем медтехнику от ведущих мировых производителей. Также в широком ассортименте представлены расходные материалы, медицинская и лабораторная мебель, товары для домашнего использования (тонометры, глюкометры, массажеры и т.д.)</br>
<br>Вы можете оформить заявку на нашем сайте и в комментарии задать все интересующие вопросы, наши менеджеры свяжутся с вами в самое ближайшее время!</br> </li>
      </ul>
      <a class="link animated fadeInUp delay-1s servicelink" href="#service">Перейти</a>
    </div>
  </header>
  <section class="main-section" id="service">
    <!--main-section-start-->
    <div class="container">
      <h2>Спецпредложение</h2>
      <h6>Расходные материалы к инсулиновым помпам для больных сахарным диабетом по спецценам !!!</h6>
      <div class="row">
        <div class="col-lg-4 col-sm-6 wow fadeInLeft delay-05s">
          <div class="service-list">
            <h2>Лучшие предложения</h2>
            <div class="service-list-col1">
              <i class="fa fa-medkit"></i>
            </div>
            <div class="service-list-col2">
              <h3><a href = "{% url 'shop'%}">СТАЦИОНАРНЫЙ СКАНЕР MYLAB 70</a></h3>
              <p>MyLab 70 – стационарный ультразвуковой универсальный аппарат экспертного класса </p>
            </div>
          </div>
          <div class="service-list">
            <div class="service-list-col1">
              <i class="fa fa-medkit"></i>
            </div>
            <div class="service-list-col2">
              <h3><a href = "{% url 'shop'%}">ПОРТАТИВНЫЙ СКАНЕР MYLAB 30</a></h3>
              <p>MyLab™30 – это идеальное сочетание размера и выполняемых функций.</p>
            </div>
          </div>
          <div class="service-list">
            <div class="service-list-col1">
              <i class="fa fa-medkit"></i>
            </div>
            <div class="service-list-col2">
              <h3><a href = "{% url 'shop'%}">СТЕРИЛИЗАТОР ВОЗДУШНЫЙ ГП-10 МО</a></h3>
              <p>Стерилизатор воздушный предназначен для стерилизации хирургических инструментов, стеклянной посуды и термостойких шприцов</p>
            </div>
          </div>
          <div class="service-list">
            <div class="service-list-col1">
              <i class="fa fa-medkit"></i>
            </div>
            <div class="service-list-col2">
              <h3><a href = "{% url 'shop'%}">ПОРТАТИВНЫЙ АВТОМАТИЗИРОВАННЫЙ ДЕФИБРИЛЛЯТОР HEARTSTART FRX</a></h3>
              <p>Портативный автоматизированный дефибриллятор FRx (формата AED), не требующий специальной медицинской подготовки</p>
            </div>
          </div>
        </div>
        <figure class="col-lg-8 col-sm-6  text-right wow fadeInUp delay-02s">

          <!-- Bootstrap 3 -->
          <div id="carousel" class="carousel slide" data-ride="carousel">
            <!-- Индикаторы -->
            <ol class="carousel-indicators">
              <li data-target="#carousel" data-slide-to="0" class="active"></li>
              <li data-target="#carousel" data-slide-to="1"></li>
              <li data-target="#carousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
              <div class="item active">
                <img src="{% static 'img/MyLab70.JPEG' %}" alt="">
              </div>
              <div class="item">
                <img src="{% static 'img/MyLab30.JPEG' %}" alt="">
              </div>
              <div class="item">
                <img src="{% static 'img/GP10.JPG' %}" alt="">
              </div>
            </div>
            <!-- Элементы управления -->
            <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
              <span class="sr-only">Предыдущий</span>
            </a>
            <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
              <span class="sr-only">Следующий</span>
            </a>
          </div>
          <!-- Bootstrap 4 -->
<div id="carousel" class="carousel slide" data-ride="carousel">
  <!-- Индикаторы -->
  <ol class="carousel-indicators">
    <li data-target="#carousel" data-slide-to="0" class="active"></li>
    <li data-target="#carousel" data-slide-to="1"></li>
    <li data-target="#carousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="img-fluid" src="" alt="">
    </div>
    <div class="carousel-item">
      <img class="img-fluid" src="" alt="">
    </div>
    <div class="carousel-item">
       <img class="img-fluid" src="" alt="">
    </div>
  </div>
  <!-- Элементы управления -->
  <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Предыдущий</span>
  </a>
  <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Следующий</span>
  </a>
</div>
        </figure>

      </div>
    </div>
  </section>
  <section class="main-section alabaster">
    <div class="container">
      <div class="row">
        <figure class="col-lg-5 col-sm-4 wow fadeInLeft">
          <img src="{% static 'img/covid.jpg' %}" alt=""> 
        </figure>
        <div class="col-lg-7 col-sm-8 featured-work">
          <h2>Полезная информация</h2>
          <div class="featured-box">
            <div class="featured-box-col1 wow fadeInRight delay-02s">
            </div>
            <div class="featured-box-col2 wow fadeInRight delay-02s">
              <h3><a href = "{% url 'innovations'%}">Инновации в области медицинского оборудования</a></h3>
            </div>
          </div>
          <div class="featured-box">
            <div class="featured-box-col1 wow fadeInRight delay-04s">
            </div>
            <div class="featured-box-col2 wow fadeInRight delay-04s">
              <h3><a href = "{% url 'postavshiki'%}">Как выбрать поставщика качественного оборудования</a></h3>
            </div>
          </div>
          <div class="featured-box">
            <div class="featured-box-col1 wow fadeInRight delay-06s">
            </div>
            <div class="featured-box-col2 wow fadeInRight delay-06s">
              <h3><a href = "{% url 'medkab'%}">Медкабинеты в образовательных учреждениях</a></h3>
            </div>
          </div>
          <div class="featured-box">
            <div class="featured-box-col1 wow fadeInRight delay-04s">
            </div>
            <div class="featured-box-col2 wow fadeInRight delay-04s">
              <h3><a href = "{% url 'sanit'%}">Оснащение санитарно-курортных учреждении</a></h3>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <section class="main-section contact" id="contact">

        <div class="row">
          <div class="col-lg-6 col-sm-7 wow fadeInLeft">
            <div class="contact-info-box phone clearfix">
              <h3><i class="fa fa-phone"></i>Телефон:</h3>
              <span>Уфа: +7(347)-292-98-90
                <br>Нефтекамск: +7(34783)-2-37-60</br>
                Москва: 8-800-77-55-118
              </span>
            </div>
            <div class="contact-info-box email clearfix">
              <h3><i class="fa fa-pencil"></i>Адрес</h3>
              <span>
                  Адрес: г.Уфа, ул. З.Биишевой, д.1
                  <br>Е-mail: bmtufa@mail.ru</span>
  <br>Адрес: Республика Башкортостан, г. Нефтекамск, ул. Янаульская, д.1л
  <br>E-mail: bmt-2008@yandex.ru
  <br>Адрес: 119435, г. Москва, Большой Саввинский переулок, д. 8с1
  <br>E-mail: bmtmoscow@yandex.ru
            </div>
          </div>
      </section>
    </div>
  </section>
  <!--business-talking-end-->

  <footer class="footer">
    <div class="container">
      <div class="footer-logo"><a href="#"><img src="{% static 'img/footer-logo.png' %}" alt=""></a></div>
      <span class="copyright">&copy; 2009-2020 ООО "БМТ". Все права защищены.</span>
      <div class="credits">
      </div>
    </div>
  </footer>

  {% endblock content %}

web/templates/web/tovar.html
{% extends 'web/main.html' %}
{% load static %}
{% block title_page %}
<title>Товар</title>
{% endblock title_page %}
{% block content %}

<style>
   .center {
    width: 700px; /* Ширина элемента в пикселах */
    padding: 10px; /* Поля вокруг текста */
    margin: auto; /* Выравниваем по центру */
   }
  </style>
  <div class="center">

    <style>
          #zatemnenie {
            background: rgba(102, 102, 102, 0.5);
            width: 100%;
            height: 100%;
            position: absolute;
            top: 0;
            left: 0;
            display: none;
          }
          #okno {
            width: 300px;
            height: 100px;
            text-align: center;
            padding: 15px;
            border: 3px solid #e3492b;
            border-radius: 10px;
            color: #000000;
            position: absolute;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            margin: auto;
            background: #fff;
          }
          #zatemnenie:target {display: block;}
          .close {
            display: inline-block;
            border: 1px solid #e3492b;
            color: #e3492b;
            padding: 0 50px;
            margin: 10px;
            text-decoration: none;
            background: #f2f2f2;
            font-size: 14pt;
            cursor:pointer;
          }
          .close:hover {background: #e6e6ff;}
        </style>

        <div id="zatemnenie">
        <div id="okno">
                <h3><i class="fa fa-phone"></i>Телефон:</h3>
                <span>Уфа: +7(347)-292-98-90
                  <br>Нефтекамск: +7(34783)-2-37-60</br>
                  Москва: 8-800-77-55-118
                </span>
          <br>
          <a href="#" class="close">Закрыть окно</a>
        </div>
      </div>

<div class="{{ product.group }}">
  <img src="{{ product.img.url }}" alt="">
  <br>{{ product.name }}

  <p><a href="#zatemnenie"><p><input type="submit" value="Купить"></p></a></p>
  <br>Цена:{{ product.price }}
  <br>Производитель:{{ product.brand }}
  <br>Модель:{{ product.model }} 
        <hr>{{ product.description }}
</div>

<!-- <p class="price">{{ product.price }}</p>
<form action="{% url 'cart:cart_add' product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Add to cart">
</form> -->
</div>

<footer class="footer">
  <div class="container">
    <div class="footer-logo"><a href="#"><img src="{% static 'img/footer-logo.png' %}" alt=""></a></div>
    <span class="copyright">&copy; 2009-2020 ООО "БМТ". Все права защищены.</span>
    <div class="credits">
    </div>
  </div>
</footer>

{% endblock content %}